TOPIC: 'focus'
LENGTH_IN_MINUTE: 60
TYPE: 'video'
RESOLUTION: '720p'
LANGUAGE: 'en'

VIDEO:
  IMAGE_QUERY: 'hill and sea'
  IMAGE_COUNT: 10
  TITLE: "A monday motivation"
  DESCRIPTION: "A monday motivation"
  HASH_TAGS: "motivation,youtubeshots,iphone"

AUDIO:
  SPEED_X: 1.0
  VOICE: 'female'

STOCK:
  AUDIO: './data_and_config/cc_audios.txt'
  VIDEO: './data_and_config/cc_videos.txt'
  REPEAT: 4
