TOPIC: 'motivation'
LENGTH_IN_MINUTE: 60
TYPE: 'video'
RESOLUTION: '720p'
LANGUAGE: 'en'

VIDEO:
  IMAGE_QUERY: 'hill and sea'
  IMAGE_COUNT: 10
  TITLE: "A monday motivation"
  DESCRIPTION: "A monday motivation"
  HASH_TAGS: "motivation,youtubeshots,iphone"

AUDIO:
  SPEED_X: 1.0
  VOICE: 'female'

STOCK:
  AUDIO: './Stock Content/Audio/Gym-Rock/temp_repeated_passion-127011.mp3, ./Stock Content/Audio/Gym-Rock/action-workout-trap-fashion-99524.mp3'
  VIDEO: './Stock Content/Video/gym/135162 (1440p).mp4, ./Stock Content/Video/gym/135156 (1440p).mp4, ./Stock Content/Video/gym/135156 (1440p).mp4'
  REPEAT: 2
